### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by nyukers**
Checking git, npm, pip

### CODE REVIEW

**Comment by mezgoodle** [comment]
Execute files if env variables are _true_
Example:
```bash
if $python then python.sh
if not $nodejs then continue
```

**Comment by nyukers** [comment]
ok, I think we fixed it just now.

**Comment by nyukers** [comment]
if [ -z ${var1} ]; then echo "var1 is unset"; else echo "var is set to '$var1'"; fi

**Comment by nyukers** [comment]
if [ "$python" = true ] then sh python.sh
I highly recommend don't use var-names as "python".

**Comment by nyukers** [comment]
Happy New Year!

**Pull request closed without merging**
